require:
  - rubocop-rails
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 2.5

Metrics/MethodLength:   
  Max: 40

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/NumericPredicate:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Rails/Exit:
  Enabled: false

Style/GuardClause:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Sorbet/HasSigil:
  Enabled: true
  MinimumStrictness: strict
  Exclude:
    - Gemfile
    - '*.gemspec'
    - 'examples/**/*.rb'
    - lib/quarantine/version.rb
    - 'spec/**/*.rb'

Sorbet/EnforceSigilOrder:
  Enabled: true

# Need to explicitly disable these
Sorbet/IgnoreSigil:
  Enabled: false

Sorbet/FalseSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: false

Sorbet/StrictSigil:
  Enabled: false

Sorbet/StrongSigil:
  Enabled: false

Sorbet/EnforceSignatures:
  Enabled: false
